name: Indy Plenum - PR Workflow
on:
  pull_request:
    paths:
      - '**'
      - "!plenum/__version__.json"
    branches:
      - main

env:
  BASE_IMAGE: ghcr.io/hyperledger/indy-plenum-base
  PROD_IMAGE: ghcr.io/hyperledger/indy-plenum

jobs:
  testsNeeded:
    name: Check if tests needed
    runs-on: ubuntu-latest
    outputs:
      testsNeeded: ${{ steps.filter.outputs.testsNeeded }}
    steps:
      - uses: actions/checkout@v4
      - name: testsNeeded
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            testsNeeded:
              - '**.py'
              - '.github/**'
              - 'Dockerfile'
              - 'Dockerfile.base'
              - 'bump_version.sh'

  docker-build-base:
    name: Build Base Image
    needs: [testsNeeded]
    if: ${{ needs.testsNeeded.outputs.testsNeeded == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build base image
        run: docker build -f Dockerfile.base -t ${{ env.BASE_IMAGE }}:latest .

  docker-build:
    name: Build Production Image
    needs: [testsNeeded, docker-build-base]
    if: ${{ needs.testsNeeded.outputs.testsNeeded == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build production image
        run: docker build -f Dockerfile -t ${{ env.PROD_IMAGE }}:latest .

  plenum_tests:
    name: Test Plenum
    needs: [testsNeeded, docker-build]
    if: ${{ needs.testsNeeded.outputs.testsNeeded == 'true' }}
    uses: ./.github/workflows/reuseable_test.yaml
    with:
      image_tag: ${{ env.PROD_IMAGE }}:latest

  statusCheck:
    name: statusCheck
    runs-on: ubuntu-latest
    needs: [testsNeeded, plenum_tests]
    if: ${{ needs.testsNeeded.outputs.testsNeeded == 'false' || success() }}
    steps:
      - run: 'echo "Just a status Check (Always true, when executed) for branch protection rules(blocks merging while test are running and if tests fail)." '
