name: Triggered by Version Bump merged

on:
  push:
    branches-ignore:
      - update-rc-version
      - update-version
    paths:
      - '!**'
      - "plenum/__version__.json"

permissions:
  contents: write
  pull-requests: write

env:
  BASE_IMAGE: ghcr.io/${{ github.repository_owner }}/indy-plenum-base
  PROD_IMAGE: ghcr.io/${{ github.repository_owner }}/indy-plenum

jobs:
  release-infos:
    name: release-infos
    runs-on: ubuntu-latest
    outputs:
      isVersionBump: ${{ steps.get-release-info.outputs.isVersionBump }}
      isPreRelease: ${{ steps.get-release-info.outputs.isRC }}
      versionTag: ${{ steps.get-release-info.outputs.versionTag }}
      version: ${{ steps.get-release-info.outputs.version }}
      component: ${{ steps.get-release-info.outputs.component }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: get-release-info
        id: get-release-info
        shell: bash
        run: |
          version=$(grep -oP "\d+.\d+.\d+((-|.)?rc\d+)?" <<< "${{ github.event.head_commit.message }}" || true)
          if [[ ! -z ${version} ]]; then
            versionTag="v${version}"
            if [[ "${version}" == *'rc'* ]]; then
              isRC=true
              component="rc"
              prBranch=update-rc-version
            else
              isRC=false
              component="stable"
              prBranch=update-version
            fi
            if [[ $(grep -oP "\[v\d+.\d+.\d+(-?rc\d+)?\]" <<< "${{ github.event.head_commit.message }}" || true) ]]; then
              isVersionBump=true
            else
              isVersionBump=false
            fi
          fi
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "versionTag=${versionTag}" >> $GITHUB_OUTPUT
          echo "isRC=${isRC}" >> $GITHUB_OUTPUT
          echo "component=${component}" >> $GITHUB_OUTPUT
          echo "prBranch=${prBranch}" >> $GITHUB_OUTPUT
          echo "isVersionBump=${isVersionBump}" >> $GITHUB_OUTPUT

  createRelease:
    name: Create Release
    needs: [release-infos]
    if: needs.release-infos.outputs.isVersionBump == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: |
            ${{ env.BASE_IMAGE }}:${{ needs.release-infos.outputs.versionTag }}
            ${{ env.BASE_IMAGE }}:latest

      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.PROD_IMAGE }}:${{ needs.release-infos.outputs.versionTag }}
            ${{ env.PROD_IMAGE }}:latest

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-infos.outputs.versionTag }}
          generate_release_notes: true
          body: |
            [${{ needs.release-infos.outputs.versionTag }}]

            Docker images:
            - `${{ env.PROD_IMAGE }}:${{ needs.release-infos.outputs.versionTag }}`
            - `${{ env.PROD_IMAGE }}:latest`
          prerelease: ${{ needs.release-infos.outputs.isPreRelease }}
          target_commitish: ${{ github.event.ref }}
          name: "${{ needs.release-infos.outputs.versionTag }}"
          token: ${{ secrets.BOT_PR_PAT }}

  convertPyVersion:
    name: "Convert to python version flavour"
    needs: [release-infos, createRelease]
    runs-on: ubuntu-latest
    outputs:
      pyVersion: ${{ steps.conversion.outputs.pyVersion }}
      debVersion: ${{ steps.conversion.outputs.debVersion }}
    steps:
      - name: Convert to python version flavour
        id: conversion
        shell: bash
        run: |
          pyVersion=$(echo ${{ needs.release-infos.outputs.versionTag }} | sed 's~v~~g')
          if [[ ${pyVersion} == *"-"* ]]; then
            pyVersion=$(echo ${pyVersion} | sed 's~-~.~g')
          fi
          echo "pyVersion=${pyVersion}" >> $GITHUB_OUTPUT
          echo "debVersion=$(echo ${pyVersion} | sed -E 's/^([^\.]*\.[^\.]*\.[^\.]*)\.(.*)$/\1~\2/')" >> $GITHUB_OUTPUT

  triggerNodeUpdate:
    runs-on: ubuntu-latest
    needs: [release-infos, createRelease, convertPyVersion]
    if: ${{ github.repository_owner == 'hyperledger' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BOT_PR_PAT }}
          repository: hyperledger/indy-node
          event-type: update-node
          client-payload: '{"dockerTag": "${{ needs.release-infos.outputs.versionTag }}", "email":"${{ github.event.pusher.email }}", "dockerOwner": "${{ github.repository_owner }}"}'
