name: Indy Plenum - Push Workflow
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '.github/**'
      - 'Dockerfile'
      - 'Dockerfile.base'
      - 'bump_version.sh'

env:
  BASE_IMAGE: ghcr.io/${{ github.repository_owner }}/indy-plenum-base
  PROD_IMAGE: ghcr.io/${{ github.repository_owner }}/indy-plenum

jobs:
  docker-build-base:
    name: Build Base Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: ${{ env.BASE_IMAGE }}:latest

  docker-build:
    name: Build Production Image
    needs: [docker-build-base]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.PROD_IMAGE }}:latest
          build-args: BASE_IMAGE=${{ env.BASE_IMAGE }}:latest

  plenum_tests:
    name: Test Plenum
    needs: [docker-build]
    uses: ./.github/workflows/reuseable_test.yaml
    with:
      image_tag: ghcr.io/${{ github.repository_owner }}/indy-plenum:latest
