name: Triggered by set Tag

on:
  push:
    tags:
      - setRelease-v**

permissions:
  contents: write
  pull-requests: write

jobs:
  taginfos:
    name: get Tag infos
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-release-info.outputs.version }}
      versionTag: ${{ steps.get-release-info.outputs.versionTag }}
      prBranch: ${{ steps.get-release-info.outputs.prBranch }}
      BASE: ${{ steps.get-branch.outputs.branch }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: extract branch
        id: get-branch
        shell: bash
        run: |
          raw=$(git branch -r --sort=-committerdate --contains ${{ github.ref }} | head -n 1)
          branch=${raw//origin\/}
          echo "branch=${branch}" >> $GITHUB_OUTPUT
      - name: get-release-info
        id: get-release-info
        shell: bash
        run: |
          version=$(grep -oP "\d+.\d+.\d+((-|.)?rc\d+)?" <<< "${{ github.ref }}" || true)
          if [[ ! -z ${version} ]]; then
            versionTag="v${version}"
            if [[ "${version}" == *'rc'* ]]; then
              isRC=true
              component="rc"
              prBranch=update-rc-version
            else
              isRC=false
              component="stable"
              prBranch=update-version
            fi
            if [[ $(grep -oP "\[v\d+.\d+.\d+(-?rc\d+)?\]" <<< "${{ github.ref }}" || true) ]]; then
              isVersionBump=true
            else
              isVersionBump=false
            fi
          fi
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "versionTag=${versionTag}" >> $GITHUB_OUTPUT
          echo "isRC=${isRC}" >> $GITHUB_OUTPUT
          echo "component=${component}" >> $GITHUB_OUTPUT
          echo "prBranch=${prBranch}" >> $GITHUB_OUTPUT
          echo "isVersionBump=${isVersionBump}" >> $GITHUB_OUTPUT

  bump_version:
    name: Bump Version Number
    needs: taginfos
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'hyperledger' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install deps for version change
        run: pip install base58 \
                      importlib_metadata==3.10.1 \
                      packaging \
                      python-dateutil \
                      msgpack-python \
                      jsonpickle
      - name: Prepare package and set version
        run: |
          ./bump_version.sh ${{ needs.taginfos.outputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          author: ${{ github.actor }} <${{ github.event.pusher.email }}>
          committer: ${{ github.actor }} <${{ github.event.pusher.email }}>
          signoff: true
          commit-message: Update Version number for v${{ needs.taginfos.outputs.version }}
          base: ${{ needs.taginfos.outputs.BASE }}
          branch: ${{ needs.taginfos.outputs.prBranch }}
          title: "[${{ needs.taginfos.outputs.versionTag }}] - Update Version Number for Release"
          body: "[${{ needs.taginfos.outputs.versionTag }}] - Update Version number for Release"
          delete-branch: true
          token: ${{ secrets.BOT_PR_PAT }}
